name: Update hosts

on:
  watch:
    types: [started]
  schedule:
   - cron:  '0 0,8 * * *'
  workflow_dispatch:

env:
  TZ: Asia/Shanghai

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [12]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - name: Update hosts
        run: npm run start
      - name: Commit
        id: commit
        run: |
          git config --local user.email "2236639958@qq.com"
          git config --local user.name "qq2236639958"
          git add .
          git commit -m "CST: $(TZ=Asia/Shanghai date "+%Y-%m-%d %H:%M:%S")"
        continue-on-error: true

      - name: Check on failures
        if: steps.commit.outputs.status == 'failure'
        run: exit 1

      - name: Push
        run: |
          git push -u origin main
