name: Update

on:
  watch:
    types: [started]
  schedule:
   - cron:  '0 0,8 * * *'
  workflow_dispatch:

env:
  TZ: Asia/Shanghai

jobs:
  Update:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      
    - name: GetTime
      id: date
      run: echo "GetTime=$(date +'%Y-%m-%d %H:%M:%S CST')" >> "$GITHUB_OUTPUT" 

    - name: Update
      run: |
        # GITHUB HOSTS
        rm -f GH-HOSTS && touch GH-HOSTS
        wget https://raw.githubusercontent.com/ineo6/hosts/master/hosts -O  GH-HOSTS1.txt && sed -i 's/ineo6/viptv-work/gi' GH-HOSTS1.txt
        sed -i 's/# 也可以关注公众号：湖中剑，保证不迷路//gi' GH-HOSTS1.txt
        cat GH-HOSTS1.txt >> GH-HOSTS
        rm -f GH-HOSTS1.txt

    - name: Clean
      run: |
        git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
        git config user.name "github-actions[bot]"
        git checkout --orphan latest_branch
        git add -A
        git commit -am "IPTV 资源更新于 ${{ steps.date.outputs.GetTime }}"
        git branch -D main
        git branch -m main
    - name: Push
      run: git push -f origin main
