name: Update hosts

on:
  watch:
    types: [started]
  schedule:
   - cron:  '0 0,8 * * *'
  workflow_dispatch:

env:
  TZ: Asia/Shanghai

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: use node
        uses: actions/setup-node@v2
        with:
            node-version: 16 # node版本
            cache: "yarn"

      - name: Run
        run: |
          bash domain2ip.sh
      - name: Update hosts
        run: npm run start
      - name: Commit
        id: commit
        run: |
          git config --local user.email "2236639958@qq.com"
          git config --local user.name "qq2236639958"
          git add .
          git commit -m "CST: $(TZ=Asia/Shanghai date "+%Y-%m-%d %H:%M:%S")"
        continue-on-error: true

      - name: Check on failures
        if: steps.commit.outputs.status == 'failure'
        run: exit 1

      - name: Push
        run: |
          git push -u origin main
